### ISSUE TITLE
Input bar

### ISSUE THREAD

**Issue by kosterm14** [kosterm14/the-web-is-for-everyone-interactive-functionality#7]
Op firefox werkt het niet goed

![image](https://user-images.githubusercontent.com/61830362/229085909-d9a8e6fa-90a7-4354-b82b-8d099ecbd417.png)

**Comment by kosterm14** [comment]
## Reden gevonden:
``` css
label,
input {
    width: -webkit-fill-available;
}
```
-webkit-fill-available werkt niet op firefox dus de width klopt niet

## Fix:
``` css
label,
input {
    width: 100%
}
```
