### ISSUE TITLE
form

### ISSUE THREAD

**Issue by kosterm14** [kosterm14/the-web-is-for-everyone-interactive-functionality#8]
Op firefox werkt de form niet goed

![image](https://user-images.githubusercontent.com/61830362/229086085-d4ad45b0-20a9-49f5-b837-414b81bf6ce4.png)

**Comment by kosterm14** [comment]
## Reden gevonden:
``` css
label,
input {
    width: -webkit-fill-available;
}
```
-webkit-fill-available werkt niet op firefox dus de width klopt niet

## Fix:
``` css
label,
input {
    width: 100%
}
```
